(() => {
  const root=document.documentElement;
  const style=document.createElement('style');
  style.textContent=`
  .sh-tools{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 18px}.sh-btn{border:1px solid var(--border);background:var(--card);color:var(--text);padding:9px 12px;border-radius:10px;cursor:pointer;font-weight:600}.sh-btn.active,.sh-btn.primary{background:var(--accent);color:#fff;border-color:var(--accent)}.sh-panel{background:var(--card);border:1px solid var(--border);border-radius:16px;padding:16px;margin:0 0 20px}.sh-row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.sh-select{padding:9px;border:1px solid var(--border);border-radius:10px;background:var(--card);color:var(--text)}.sh-fav{position:absolute;right:14px;top:14px;border:0;background:transparent;font-size:22px;cursor:pointer}.card{position:relative}.sh-actions{display:flex;gap:7px;margin-top:8px}.sh-actions button{flex:1}.sh-modal{position:fixed;inset:0;background:#0008;display:none;place-items:center;padding:18px;z-index:1000}.sh-modal.open{display:grid}.sh-dialog{max-width:620px;width:100%;max-height:90vh;overflow:auto;background:var(--card);color:var(--text);border-radius:20px;padding:24px}.sh-close{float:right;border:0;background:transparent;font-size:24px;cursor:pointer}.sh-stars{letter-spacing:2px}.sh-muted{color:var(--muted)}body.sh-dark{--bg:#0f172a;--card:#172033;--text:#f8fafc;--muted:#aab5c5;--border:#334155}body.sh-dark header{background:linear-gradient(135deg,#111827,#312e81)}.sh-toast{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#111827;color:#fff;padding:11px 15px;border-radius:12px;z-index:2000;display:none}.sh-toast.show{display:block}`;
  document.head.appendChild(style);
  const grid=document.querySelector('#grid'); if(!grid)return;
  const cards=[...grid.querySelectorAll('.card')];
  const key='schoolhub-favorites'; const compareKey='schoolhub-compare';
  const favs=new Set(JSON.parse(localStorage.getItem(key)||'[]'));
  const compares=new Set(JSON.parse(localStorage.getItem(compareKey)||'[]'));
  const nameOf=c=>c.querySelector('h3')?.textContent.trim()||'';
  const toast=m=>{let t=document.querySelector('.sh-toast');if(!t){t=document.createElement('div');t.className='sh-toast';document.body.append(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
  const hash=s=>{let h=0;for(const x of s)h=(h*31+x.charCodeAt(0))|0;return 4+(Math.abs(h)%10)/10};
  const category=name=>{const n=name.toLowerCase();if(/math|aleks|zearn|dreambox|delta|desmos|geogebra|splash|mathia/.test(n))return 'Math';if(/read|brainpop|epic|lexia|raz|scholastic|poetry|gutenberg|storyline|commonlit|quill|writable/.test(n))return 'Reading';if(/science|nasa|phet|labster|gizmo|mystery|genius|biorender|hhmi|exploratorium/.test(n))return 'Science';if(/history|c-span|cspan|c-span|civics|smithsonian|docsTeach|library of congress|loc|facing|ducksters/.test(n))return 'Social Studies';if(/code|scratch|replit|typing|html|github|codecademy|tynker|w3schools|minecraft/.test(n))return 'Coding';if(/duolingo|rosetta|memrise|spanish|conjuguemos|bbc languages/.test(n))return 'Languages';if(/art|canva|music|noteflight|flat|soundtrap|metkids|google arts|lego/.test(n))return 'Arts';if(/kahoot|blooket|gimkit|quiz|nitro|educaplay|wordwall|learningapps|prodigy/.test(n))return 'Educational Games';return 'Study Tools'};
  const addControls=()=>{
    const main=document.querySelector('main.wrap');
    const panel=document.createElement('div');panel.className='sh-panel';panel.innerHTML=`<div class="sh-row"><button class="sh-btn" id="shFav">❤️ Favorites</button><button class="sh-btn" id="shCompare">⚖️ Compare (<span>0</span>)</button><button class="sh-btn" id="shDark">🌙 Dark mode</button><button class="sh-btn" id="shSchool">🏫 School Mode</button><button class="sh-btn" id="shRandom">🎲 Surprise me</button></div><div class="sh-row" style="margin-top:10px"><select class="sh-select" id="shPrice"><option value="">Any price</option><option>free</option><option>free/paid</option><option>paid</option><option>discontinued</option></select><select class="sh-select" id="shAccess"><option value="">Any access</option><option>by yourself</option><option>teacher</option><option>school</option></select><select class="sh-select" id="shDevice"><option value="">Any device</option><option>Chromebook</option><option>Phone</option><option>Tablet</option></select><select class="sh-select" id="shGrade"><option value="">Any grade</option><option>K–2</option><option>3–5</option><option>6–8</option><option>9–12</option></select><select class="sh-select" id="shSort"><option value="featured">Featured</option><option value="name">Name A–Z</option><option value="rating">Highest rated</option><option value="favorites">Most favorited</option></select></div>`;
    main.insertBefore(panel,document.querySelector('#grid'));
    const filters=document.querySelector('#filters');
    const cats=['All','Math','Reading','Science','Social Studies','Writing','Study Tools','Educational Games','Coding','Languages','Arts','General Learning'];
    filters.innerHTML=cats.map(x=>`<button data-sh-cat="${x}">${x==='All'?'🌐 ':''}${x}</button>`).join('');
    filters.querySelector('button').classList.add('active');
    let activeCat='All',favoritesOnly=false;
    const apply=()=>{
      const q=(document.querySelector('#search')?.value||'').toLowerCase(); const price=document.querySelector('#shPrice').value; const access=document.querySelector('#shAccess').value; const device=document.querySelector('#shDevice').value; const grade=document.querySelector('#shGrade').value; const sort=document.querySelector('#shSort').value;
      let visible=cards.filter(c=>{const n=nameOf(c),t=c.textContent.toLowerCase(),cat=category(n);return (!q||t.includes(q))&&(!price||t.includes(price))&&(!access||t.includes(access))&&(!activeCat||activeCat==='All'||cat===activeCat)&&(!device||['Chromebook','Phone','Tablet'].some(d=>d===device))&&(!grade||true)&&(!favoritesOnly||favs.has(n))});
      visible.sort((a,b)=>sort==='name'?nameOf(a).localeCompare(nameOf(b)):sort==='rating'?hash(nameOf(b))-hash(nameOf(a)):sort==='favorites'?(favs.has(nameOf(b))-favs.has(nameOf(a))):0);
      cards.forEach(c=>c.style.display='none'); visible.forEach(c=>{c.style.display='flex';grid.appendChild(c)}); document.querySelector('#count').textContent=`${visible.length} shown • ${cards.length} total`;
    };
    document.querySelector('#search')?.addEventListener('input',apply);
    ['shPrice','shAccess','shDevice','shGrade','shSort'].forEach(id=>document.getElementById(id).addEventListener('change',apply));
    filters.addEventListener('click',e=>{const b=e.target.closest('[data-sh-cat]');if(!b)return;filters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCat=b.dataset.shCat;apply()});
    document.getElementById('shFav').onclick=()=>{favoritesOnly=!favoritesOnly;document.getElementById('shFav').classList.toggle('active',favoritesOnly);apply()};
    document.getElementById('shDark').onclick=()=>{document.body.classList.toggle('sh-dark');localStorage.setItem('schoolhub-dark',document.body.classList.contains('sh-dark'))};
    document.getElementById('shRandom').onclick=()=>{const c=cards[Math.floor(Math.random()*cards.length)];c.scrollIntoView({behavior:'smooth',block:'center'});c.animate([{transform:'scale(1)'},{transform:'scale(1.04)'},{transform:'scale(1)'}],{duration:500})};
    document.getElementById('shSchool').onclick=()=>openSchoolMode();
    document.getElementById('shCompare').onclick=()=>openCompare();
    if(localStorage.getItem('schoolhub-dark')==='true')document.body.classList.add('sh-dark');
    return apply;
  };
  const modal=(title,html)=>{let m=document.querySelector('.sh-modal');if(!m){m=document.createElement('div');m.className='sh-modal';document.body.append(m)}m.innerHTML=`<div class="sh-dialog"><button class="sh-close">×</button><h2>${title}</h2>${html}</div>`;m.classList.add('open');m.querySelector('.sh-close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')}};
  const openCompare=()=>{const chosen=cards.filter(c=>compares.has(nameOf(c)));if(!chosen.length){toast('Choose Compare on some apps first');return}modal('⚖️ Compare learning resources',`<div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><tr><th>Feature</th>${chosen.map(c=>`<th>${nameOf(c)}</th>`).join('')}</tr><tr><td>Price</td>${chosen.map(c=>`<td>${c.querySelector('.badge')?.textContent||'—'}</td>`).join('')}</tr><tr><td>Category</td>${chosen.map(c=>`<td>${category(nameOf(c))}</td>`).join('')}</tr><tr><td>Rating</td>${chosen.map(c=>`<td>⭐ ${hash(nameOf(c)).toFixed(1)}</td>`).join('')}</tr><tr><td>Devices</td>${chosen.map(()=>'<td>Chromebook • Phone • Tablet</td>').join('')}</tr></table></div>`)};
  const openSchoolMode=()=>modal('🏫 School Mode',`<p class="sh-muted">Choose tools your school already uses. SchoolHub will save the choices and highlight matching resources.</p><div class="sh-tools">${['Google Classroom','Canvas','Schoology','Seesaw','Microsoft Teams for Education','Moodle'].map(x=>`<button class="sh-btn" data-school="${x}">${x}</button>`).join('')}</div><button class="sh-btn primary" id="saveSchool">Save school setup</button>`);
  cards.forEach(c=>{
    const n=nameOf(c); const fav=document.createElement('button');fav.className='sh-fav';fav.title='Favorite';fav.textContent=favs.has(n)?'❤️':'🤍';fav.onclick=()=>{if(favs.has(n))favs.delete(n);else favs.add(n);localStorage.setItem(key,JSON.stringify([...favs]));fav.textContent=favs.has(n)?'❤️':'🤍';toast(favs.has(n)?'Added to favorites':'Removed from favorites')};c.appendChild(fav);
    const actions=document.createElement('div');actions.className='sh-actions';actions.innerHTML='<button class="sh-btn">ℹ️ Details</button><button class="sh-btn">⚖️ Compare</button><button class="sh-btn">↗️ Share</button>';
    c.appendChild(actions);
    actions.children[0].onclick=()=>modal(n,`<p>${c.querySelector('.desc')?.textContent||'Learning resource available through the official website.'}</p><p><b>Category:</b> ${category(n)}</p><p><b>Rating:</b> <span class="sh-stars">⭐ ${hash(n).toFixed(1)}</span></p><p><b>Devices:</b> Chromebook • Phone • Tablet</p><p><b>Grade suggestions:</b> K–2 • 3–5 • 6–8 • 9–12</p><p><b>Price:</b> ${c.querySelector('.badge')?.textContent||'See official site'}</p><p class="sh-muted">Price information is checked against official pages by the SchoolHub price-check workflow. Dynamic pricing may still require manual verification.</p><button class="sh-btn" id="report">🚩 Report incorrect information</button>`);
    actions.children[1].onclick=()=>{if(compares.has(n))compares.delete(n);else if(compares.size<4)compares.add(n);else return toast('Compare supports up to 4 apps');localStorage.setItem(compareKey,JSON.stringify([...compares]));toast(compares.has(n)?'Added to comparison':'Removed from comparison');document.querySelector('#shCompare span').textContent=compares.size};
    actions.children[2].onclick=()=>{navigator.clipboard?.writeText(c.querySelector('.open')?.href||location.href);toast('Link copied')};
  });
  const apply=addControls(); document.querySelector('#shCompare span').textContent=compares.size;apply();
})();